user_name = str(input("What is you name? "))
print(f"Hi {user_name}. Nice to meet you !!!")
print("Hi {user_name}. Nice to meet you !!!")
print("Hi " + user_name + ". Nice to meet you !!!")
print("Hi ", user_name, ". Nice to meet you !!!")
